trigger:
- main

variables:
  imageName: webapp
  acrName: myacr31044.azurecr.io

pool:
  name: SelfHosted

steps:
- task: Docker@2
  displayName: Build and Push Image
  inputs:
    containerRegistry: myacr31044
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: Dockerfile
    tags: |
      dev-$(Build.BuildId)
